server:
  port: 8080
  servlet:
    context-path: /identify

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/mydatabase"
    driver-class-name: "org.postgresql.Driver"
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  mapper-locations: "classpath:mappers/*.xml"
  type-aliases-package: "com.phong.identify_service.entity"
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  signerKey: "cQk9bALPSDufXzWjCgkNAnJ1jUSVgDM0omqPmsnRs77H9kez1icEJ8F6NYWLaWgM"