server:
  port: 8080
  servlet:
    context-path: /identify

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/mydatabase"
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "cQk9bALPSDufXzWjCgkNAnJ1jUSVgDM0omqPmsnRs77H9kez1icEJ8F6NYWLaWgM"